# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-26 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetwork_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date checkout'),
        ),
    ]
