# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-22 03:30
from __future__ import unicode_literals

import SocialNetwork_API.models.user_types
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetwork_API', '0002_auto_20170521_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expired_at', models.DateTimeField(default='2000-10-10 00:00:00')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField()),
                ('token', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=40)),
                ('type', SocialNetwork_API.models.user_types.PositiveTinyIntegerField(default=0)),
                ('app_id', models.CharField(default='', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sn_apis',
            },
        ),
    ]
