# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-22 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetwork_API', '0003_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='api',
            name='device',
        ),
        migrations.RemoveField(
            model_name='api',
            name='expired_at',
        ),
        migrations.RemoveField(
            model_name='api',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='api',
            name='type',
        ),
        migrations.RemoveField(
            model_name='api',
            name='version',
        ),
    ]
